services:
  client:
    image: client:dev
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  server:
    image: server:dev
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./secrets:/secrets:ro # Mount secrets folder as read-only
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=5001
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/secrets/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=DEVCERT
    env_file:
      - ./server/.env # Load the .env file located in the 'server' folder
#networks:
#  app-network:
#    driver: bridge
